Feature/145 external housing available base data structure
GazeDev/housingdb_api pull request #74
Opened 2020-07-14 14:25 UTC by JaniceHe26

Added External Housing Available Base Data Structure.

2020-07-15 16:33 UTC, zaclittleberry commented
# All
status should just be a Sequelize.STRING. enum or something else isn't necessarily a bad choice, but we don't know what those values will be and string will be more flexible for us.

the module you added should be added to lib/modules.js. You might get compilation errors after that because now your code is actually being run and it has problems. This is the right path to take, and work through those errors.

*.routes.js and *.controllers.js should have the outer structure of those files in them. basically, the module.exports statement, and the bare structure to get to their return statments. the returns can just be [] and {} for routes and controllers respectively.

AuthorId and location will be added via association. they don't get defined as fields on the 'main' part of the model.

# Janice

I know it's verbose, but can you change ExternalHousing to ExternalHousingAvailable. Otherwise it will end up conflicting with ExternalHousingWanted if/when we make that (if we followed the same pattern).

looks like there's no newline at the end of your files. This is preferred by git. There might be a setting in your editor to do this automatically when you save files.

numberOfBeds and numberOfBaths can be changed to just beds and baths

no need for the id and api models right now, should be removed. We'll add those when we get to routes.

2020-07-15 16:34 UTC, zaclittleberry requested changes
see comments in conversation tab

2020-07-16 00:02 UTC, VitaRox reviewed
Looks good to me!  It makes me wonder if I should've included those imports in my skeletal controller and routes.js files.  Anyway, looks great!

2020-07-16 14:41 UTC, zaclittleberry requested changes
looks very clean. just a few lines to remove from the model, and a few things to add as associations. you can try this before mtg if you have time and then we can go over it as a group. good job. (author and location should have examples on the property content type you can pull from).

2020-07-16 14:41 UTC, zaclittleberry commented on lib/external-housing-available/external-housing-available.models.js
> +      author: Sequelize.STRING,
please remove. should be an association, not defined this way.

2020-07-16 14:41 UTC, zaclittleberry commented on lib/external-housing-available/external-housing-available.models.js
> +      location: Sequelize.STRING,
please remove. should be an association, not defined this way.

2020-07-16 14:41 UTC, zaclittleberry commented on lib/external-housing-available/external-housing-available.models.js
> +    return ExternalHousingAvailable;
we'll still need to define associations for this model. We can go over this as a group. I can't remember if I told you all to hold off on that or give it a shot. my apologies.

2020-07-20 14:17 UTC, zaclittleberry approved these changes

2020-07-20 14:17 UTC, merged