Feature/154 external housing available read endpoint
GazeDev/housingdb_api pull request #85
Opened 2020-08-17 20:33 UTC by JaniceHe26

Added read one route and controller endpoint for external housing available.

2020-08-17 20:34 UTC, JaniceHe26 commented
<img width="1063" alt="Screen Shot 2020-08-17 at 4 25 58 PM" src="https://user-images.githubusercontent.com/36203100/90441763-898b7600-e0a7-11ea-92dd-d1bed1500d6b.png">

2020-08-25 01:07 UTC, zaclittleberry requested changes
just that small change with the .then .catch and then it looks all good.

2020-08-25 01:07 UTC, zaclittleberry commented on lib/external-housing-available/external-housing-available.controllers.js
> +    });
remember, we don't want to use then or catch in our db helper functions anymore. catching here would actually prevent us from entering the catch in our try...catch where we'd properly throw a boom error. This is something that needs to be cleaned up elsewhere at another time, but for now we at least don't want to grow our problem.

2020-08-25 19:34 UTC, zaclittleberry approved these changes

2020-08-25 19:43 UTC, zaclittleberry requested changes
you made an un-needed addition! :P I am in favor of semicolons practically everywhere they are optional, but in this case no semi-colon goes there. It shouldn't break anything, mainly because the parser should ignore it, but since these functions aren't being assigned to a variable, there is no need for semicolon. This stackoverflow answers it better: https://stackoverflow.com/a/1834674

2020-08-28 01:01 UTC, zaclittleberry approved these changes

2020-08-28 01:02 UTC, merged